### ISSUE TITLE
BUG - Drag formulation review

### ISSUE THREAD

**Issue by bjnieuwboer** [SedFoam/sedfoam#109]
Dear Cyrille,

I am quite interested in the new developments of sedfoam and I am happy that it will be added as a module to openfoam. I am mainly using the driftflux solver for rotating geometries in dredging applications. For bigger material I am planning to use sedfoam. Therefore I am glad to see that you are working on implementing the dynamic mesh. Can you tell me what the status of this implementation is?

The Dallavalle drag formulations in sedfoam is in my opinion incorrect. In Enwald1996 Equation 99 stats Cd = (0.63 + 4.8*sqrt(1/Re))^2 . This is different than the equation implemented. A WenYu type of hindered setting is used. A better name might be: DallavalleWenYu. 

Thank you for looking into this.

Bas Nieuwboer

edited: removed comment on GidaspowSchillerNaumann, since openfoam uses the same name.

**Comment by CyrilleBonamy** [comment]
Hello Bas,
Thank you very much for the issue and sorry for the response time. In France, it's the summer break.
Regarding the dynamic mesh functionality, a "pre-alpha" version is existing. It looks good but it is not validated. We hope to officially publish this one in the next few months. But if you wish you can test it (without guarantee of validity).
Regarding the Dalavalle formulation, @remichassagne will provide an answer very soon.
Thanks again for your comments.
Cyrille

**Comment by remichassagne** [comment]
Hello Bas,

Sorry for my late answer and thank you for your careful reading.

In fact both formulations are almost equivalent (same asymptotes at low and high Reynolds number) and both are proposed in the book of Dalla Valle (eq. 2.14 and 2.15 of the book).

Concerning the hindrance correction, we apply the correction proposed by Li & Sawamoto (1995). We could rename in DallaValleLiSawamoto if you prefer.

Thank you for your comments,
Rémi

**Comment by bjnieuwboer** [comment]
Hi Rémi,

Thanks for the reply. Now it was my turn to reply late, due to my holiday. 

I must admit that I haven't looked in the book of Dalla Valle and therefor did not know this form of the drag relation. Other literature generally use the other formulation and that is why I thought it was wrong. However, the reference used in the H-file to to the Enwald (1996) would be incorrect, since they use a different version of the Dalla Valle drag than is used. In that paper they use the form I described in the first post.

The name you propose would be better indeed. I cannot access the Li & Sawamoto (1995) paper. If they use the Dalla Valle drag in the form used in the solver, it would be better to reference to that paper instead of the other papers.

Kind regards,

Bas
