### ISSUE TITLE
Feature-Request

### ISSUE THREAD

**Issue by KutalmisBercin** [SedFoam/sedfoam#15]
Hi,

I wonder if you can seek for ways to make `sedFoam` as a submodule to OpenFOAM official? For example, OpenQBMM has recently been released in OpenFOAM v1912 as a submodule. It would be a win-win for the users and your code suite, in my opinion.

To that end, I would create a feature request in GitLab repo.

Kind regards

**Comment by CyrilleBonamy** [comment]
Hello
I think it's a very good idea
Let us know when you open the issue on gitlab
Cyrille

**Comment by HerpesFreeEngineer** [comment]
Hello,

Shouldn't the maintainers of sedFoam issue this request in GitLab? When I said "I would", I meant "if I were you". :) Do I miss something?

Kind regards

**Comment by CyrilleBonamy** [comment]
no you don't miss anything, but if you make a request regarding your desire to have sedfoam in openfoam 1912, it may allow us to take the opportunity to request to be added as a module.

Thanks to you for your idea :-)

**Comment by HerpesFreeEngineer** [comment]
Here we go :)

https://develop.openfoam.com/Development/openfoam/issues/1601

Please feel free to correct my remarks thereat.

The developers of OpenFOAM are very open-minded people, but also rationale and realistic. So now I pass my turn to you.

Many thanks for your interest, and prompt replies.

**Comment by CyrilleBonamy** [comment]
For your information, I started the discussion with openfoam.com.
I hope that sedfoam will be available soon on the development branch.

**Comment by AlbertoPa** [comment]
Hello Cyrille,

I am involved in the multiphase technical committee (https://wiki.openfoam.com/Multiphase_Technical_Committee) and I have suggested to consider sedFoam for inclusion during our most recent meeting. If this is still of interest to you, could you please send me an email (apcfd@outlook.com)?

Regards,
Alberto
