### ISSUE TITLE
Scaling issue

### ISSUE THREAD

**Issue by AndreyBritov** [SedFoam/sedfoam#167]
Hi,
First thing first - thank you for such useful solver. I have tried to apply it for my task, which represented by 2D scour around subsea construction. Tutorial 2DPipelineScour was taken as example. When it was scaled by 100 times, I faced an issue - scour formed not beneath cylinder but near outlet patch (attached picture). Is it can be fixed? What kind of parameter and where (I found that some parameters such as U.a, U.b and alpha.a must be changed) I need to change, to make tutorial works for cases that 100 times bigger, than initial?
![image](https://user-images.githubusercontent.com/86724415/219968250-a89e7b39-695f-4f39-9ee5-9401ba9141f8.png)

**Comment by jchauchat** [comment]
Dear Andrey,
We never tried full scale applications. The issue you are facing is probably due to the cell size near the outlet, we already face this type of problem even at small scale. Maybe you can try to refine the grid near the outlet around the bed interface.
Best regards,
Julien

**Comment by AndreyBritov** [comment]
Dear Julien,
Thank you for your reply! I have tried to refine mesh near the outlet , but problem is not ran out. Sooner or later case in crushing with tremendous velocity at down-right corner. Maybe there is some kind of scaling factor or constant in equations, that allow to make simulation only for small scale applications?
![image](https://user-images.githubusercontent.com/86724415/225592563-6f7cab18-f2bd-47e6-b722-fb9b0b3ddad9.png)
![image](https://user-images.githubusercontent.com/86724415/225592713-b167829c-e4d1-4b85-bccf-22620b9371e0.png)

**Comment by jchauchat** [comment]
If I remember correctly, there must be a wall at the bottom part of the outlet ? If not try that, the velocity should not increase like that at the corner of two walls. 
Best regards,
Julien

**Comment by AndreyBritov** [comment]
Yes, you are right, bottom patch is the wall with fixed value 0, but velocity increasing a little above the bottom. Also, the rbgh pressure seems weard.
![image](https://user-images.githubusercontent.com/86724415/225598110-298d51e4-7a4a-4816-9891-25c9f464b1ef.png)

![image](https://user-images.githubusercontent.com/86724415/225597878-31f6860a-67fa-49e0-be9e-c8324738aa0d.png)

**Comment by AndreyBritov** [comment]
Dear Julien,
Thank you for an excellent idea! I have devided outlet patch into two parts, make down patch a wall and rise it to a level of deviding line. Now everything works fine!

**Comment by CyrilleBonamy** [comment]
Very good news. So i close the issue 👍
