### ISSUE TITLE
Docker image based on Ubuntu 22.04?

### ISSUE THREAD

**Issue by paugier** [SedFoam/sedfoam#172]
Ubuntu 22.04 comes with Python 3.10, which would be useful for testing fluidsimfoam...

**Comment by paugier** [comment]
Currently, the docker images are based on (see https://github.com/SedFoam/sedfoam/blob/master/docker/Dockerfile) opencfd/openfoam2106-default (https://hub.docker.com/r/opencfd/openfoam2106-default) 

Unfortunately, there is no image opencfd/openfoam2206-default but only https://hub.docker.com/r/opencfd/openfoam-default (which is based on Ubuntu 22.04).

The dockerfiles used by opencfd are there https://develop.openfoam.com/packaging/containers

**Comment by paugier** [comment]
Actually, the sedfoam docker image is already based on Ubuntu 22.06. This is done here in the `develop` branch:  https://github.com/SedFoam/sedfoam/blob/develop/docker/Dockerfile

Why do you have `master` and `develop` branches?

**Comment by CyrilleBonamy** [comment]
We have discussed this point at length internally.
In the end, our current point of view is to release on the master branch only the big releases, which have been fully tested and validated (and which correspond to a paper), while the develop branch contains implementations of which we are not totally sure. Of course, the 1D tests (CI) always pass and give the desired results, but we sometimes have doubts about small details of the model.

Note that a new release is planned very soon (the improved kinetic theory model of the develop version has just been accepted for publication in JFM).

And yes, the sedfoam docker matches the develop branch as explained here: https://sedfoam.github.io/sedfoam/howtodocker.html
Maybe this is not explicit enough.

**Comment by paugier** [comment]
In the doc the address is 

```
Dockerfile : https://github.com/SedFoam/sedfoam/blob/master/docker/Dockerfile
```

**Comment by CyrilleBonamy** [comment]
oh yes... We have to change that. I'm reopening the issue to think about it

**Comment by CyrilleBonamy** [comment]
Done #175
