### ISSUE TITLE
alpha.a values are not getting updated

### ISSUE THREAD

**Issue by eeLegacy** [SedFoam/sedfoam#179]
Hello! I have been trying to simulate the erosion process around group of cylinders due to oscillatory flows. I used the forceProperties file to assign the gradPOSC and wave period. The velocity field looks reasonable so the vortices but the alpha.a field does not change. I used MuI rheology and dynamic Lagrangian LES model. Please let me know if I should provide the simulation files etc.
Thanks.

**Comment by CyrilleBonamy** [comment]
Thank you very much for your interest
Try imposing "minIter 1 ;" for the alpha equation in the fvSolution file.

**Comment by eeLegacy** [comment]
Thanks, it worked.

**Comment by eeLegacy** [comment]
Thansk, it worked!
