### ISSUE TITLE
Velocity Increasing Drastically

### ISSUE THREAD

**Issue by risktaker5** [SedFoam/sedfoam#186]
I am working on a project, and try to run the simulation with sedfoam solver. But my velocity is increasing very drastically in the initial stage of the simulation. Please help me regarding that. Attaching my 0_org files, constant, system files with this. Also attaching a sample diagram, what we want to achieve with this simulation. 
![WhatsApp Image 2024-03-19 at 01 31 54_f9fc6acc](https://github.com/SedFoam/sedfoam/assets/116704893/7ef9d60e-b4e1-48af-9ff5-4dc2174c7358)

[prob.zip](https://github.com/SedFoam/sedfoam/files/14641655/prob.zip)

**Comment by CyrilleBonamy** [comment]
I played quickly with your case.
I think you need to defined the patches, and in particular the step should be a wall patch
In addition, you need to run a 2D simulation and therefor consider an empty patch for the front and rear sides.

And i have the feeling that the inlet boundary conditions are not right : they are not consistent with your initialization and are not the solution of a free channel computation. Perhaps you could consider a 1D2C (one dimensional, two components) computation and impose is as the inlet boundary condition.
