### ISSUE TITLE
BUG - Compilation Errors While Installing sedFoam v2312 from develop Branch on Stampede3

### ISSUE THREAD

**Issue by benjaminb115** [SedFoam/sedfoam#192]
I encountered installation issues with sedFoam v2312 on the Stampede3 cluster while using the develop branch. The compilation fails with errors related to ambiguous conversions in overSedDymFoam.C and missing includes, specifically for uintptr_t.

To Reproduce

Load the required modules on Stampede3.
Clone the sedFoam repository from the develop branch:
git clone --branch develop --recurse-submodules https://github.com/sedfoam/sedfoam.git
Navigate to the sedFoam directory:
cd sedfoam
Run the installation commands:
./Allwclean
./Allwmake -prefix=group
Observe the compilation errors.

Expected behavior
I expected the installation to complete successfully without errors, allowing me to use sedFoam v2312 with OpenFOAM v2312.

Error Messages
During compilation, the following errors were encountered:
overSedDymFoam.C: In function ‘Foam::word Foam::name(const void*)’:
error: ‘uintptr_t’ was not declared in this scope

OS: Linux (e.g., CentOS 7)
OpenFOAM Version: OpenFOAM v2312
Additional context
I have swak4Foam installed, which is required for sedFoam. However, I am unsure if there are compatibility issues between sedFoam v2312 and OpenFOAM v2312.

**Comment by CyrilleBonamy** [comment]
Hello.
Thank you for opening issue.
There is no compatibility issues between sedfoam v2312 and openfoam v2312.

I have the feeling that your problem is related to the gcc version (>=13) as explained here: https://www.mail-archive.com/debian-science-maintainers@alioth-lists.debian.net/msg46485.html

What is your gcc version? And if that's the problem, maybe you can try with openfoam 2406 or open an issue on https://develop.openfoam.com/.

**Comment by benjaminb115** [comment]
Hello Cyrille,

Thank you for getting back to me.

I installed OpenFOAM v2306 on the cluster and successfully ran the laminar
tutorials. However, I encountered an issue when attempting to run RAS
tutorial cases like 2Dscour or 3Dscour. The case attempts to generate the
libcodeStream library, but it fails to load the shared object file.
Specifically, I get the following error:

Could not load
"/home/bb115/Example/2DScour/1D/dynamicCode/platforms/linux64GccDPInt32Opt/lib/libcodeStream_3330e45287ee31d4f883712c6f7882f72936fb17.so"
/home/bb115/Example/2DScour/1D/dynamicCode/platforms/linux64GccDPInt32Opt/lib/libcodeStream_3330e45287ee31d4f883712c6f7882f72936fb17.so:
cannot open shared object file: No such file or directory.

Even though the library file is generated, it seems unable to load it. I
have reviewed several threads and comments on the CFD-Online forum, but I
haven’t found a definitive solution to this issue. Any guidance on how to
resolve this would be greatly appreciated.

Best,

Benjamin

**Comment by CyrilleBonamy** [comment]
Hello Benjamin,

Can you confirm that the libcodeStream_3330e45287ee31d4f883712c6f7882f72936fb17.so is generated and can be found at the following location : /home/bb115/Example/2DScour/1D/dynamicCode/platforms/linux64GccDPInt32Opt/lib/libcodeStream_3330e45287ee31d4f883712c6f7882f72936fb17.so

If so, I guess there is a problem in the bashrc file of the openfoam installation.

Send me all the log files to check.

**Comment by benjaminb115** [comment]
For your information, I am attaching the .bashrc file from my *home
directory on the cluster*. This is the user-specific configuration,
separate from the one in the OpenFOAM core installation directory.

The previously shared bashrc file was from the OpenFOAM system installation
directory.

Best,

Benjamin

**Comment by CyrilleBonamy** [comment]
I can't find your attached files. Perhaps github has deleted the attached files?

**Comment by benjaminb115** [comment]
[.bashrc.txt](https://github.com/user-attachments/files/17260011/default.bashrc.txt)
[log.txt](https://github.com/user-attachments/files/17260012/log.txt)
[bashrc.txt](https://github.com/user-attachments/files/17260013/bashrc.txt)
Yes, indeed github does not support the original files. I attached them as txt files.

**Comment by benjaminb115** [comment]
Hello Cyrille,

I am following up on our previous conversation regarding the installation issues I've been experiencing with sedFoam v2306 on the Stampede3 cluster. Have you had a chance to review the log files and the .bashrc file I sent over?

**Comment by CyrilleBonamy** [comment]
Hello Benjamin,
Sorry for the delay.
I've just read the log file. I'm very surprised because there's no bug, nothing... The sedfoam process stops for no reason. 
As far as I'm concerned, the issue isn't with sedfoam but with openfoam itself. It's probably related to the openfoam's dynamic code and not to sedfoam.
Sorry.
