### ISSUE TITLE
The 1d_profil folder was not generated after running the 3DScour/1D case.

### ISSUE THREAD

**Issue by dml177825934065** [SedFoam/sedfoam#195]
Hello, I encountered an issue while running the 3DScour case, and any response would be greatly appreciated.
My OpenFOAM version is v2406. After running ./Allrun.pre, I couldn't find the 1d_profil folder under the $FOAM_CASE path, which results in the required initialization files being missing. Could you please help me ?
Thank you!

**Comment by CyrilleBonamy** [comment]
Hello,
Thank you for your interest in sedfoam.
It is normal that the Allrun.pre script does not create the 1d_profil directory.
However, if you read the Allrun script, you'll see that the first command is a python command using the fluidfoam package. It is this command that creates the 1d_profil directory.
For debugging purposes, you can run the command creating 1d_profil separately: `python3 -c "import fluidfoam; fluidfoam.create1dprofil('1D', '.', '300', 'Y', ['U.a', 'U.b', 'alpha.a', 'k.b', 'p_rbgh', 'omega.b'])"`
Kind regards,

**Comment by dml177825934065** [comment]
Thank you for the response. It was my oversight. I didn't notice that.
