### ISSUE TITLE
Error while making sedFoam

### ISSUE THREAD

**Issue by alda30** [SedFoam/sedfoam#27]
Hi,

I'm trying to install sedFoam. I already have openFoam8 installed on my Ubuntu machine.
When I try to run "./Allwmake" I get a few errors regarding not finding specific headers of phased flows:

/opt/openfoam8/src/OSspecific/POSIX/lnInclude/PhaseIncompressibleTurbulenceModel.H:40:10: fatal error: incompressibleTurbulenceModel.H: No such file or directory

In file included from sedFoam.C:60:
/opt/openfoam8/src/OSspecific/POSIX/lnInclude/PhaseIncompressibleTurbulenceModel.H:40:10: fatal error: incompressibleTurbulenceModel.H: No such file or directory
   40 | #include "incompressibleTurbulenceModel.H"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

...
   40 | #include "incompressibleTurbulenceModel.H"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [/opt/openfoam8/wmake/rules/General/transform:26: Make/linux64GccDPInt32Opt/sedFoam_MULES.o] Error 1

Appreciate your help
Regards,
Alx

**Comment by alda30** [comment]
Actually, I tried copying and pasting the missing libraries from openfoam source.
Those errors are resolved, but I am facing another one as below:

`/usr/bin/ld.bfd: /usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib/libturbulenceModels.so: undefined reference to `Foam::IPstream::IPstream(Foam::UPstream::commsTypes, int, int, int, int, Foam::IOstreamOption::streamFormat, Foam::IOstreamOption::versionNumber)'
/usr/bin/ld.bfd: /usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib/libturbulenceModels.so: undefined reference to `Foam::orientedType::orientedType()'
/usr/bin/ld.bfd: /usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib/libincompressibleTurbulenceModels.so: undefined reference to `Foam::transform(Foam::orientedType const&)'
/usr/bin/ld.bfd: /usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib/libincompressibleTurbulenceModels.so: undefined reference to `Foam::operator&&(Foam::orientedType const&, Foam::orientedType const&)'
/usr/bin/ld.bfd: /usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib/libincompressibleTurbulenceModels.so: undefined reference to `Foam::pow3(Foam::orientedType const&)'
/usr/bin/ld.bfd: /usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib/libturbulenceModels.so: undefined reference to `Foam::UOPstream::write(Foam::token const&)'
/usr/bin/ld.bfd: /usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib/libincompressibleTurbulenceModels.so: undefined reference to `Foam::pow4(Foam::orientedType const&)'
/usr/bin/ld.bfd: /usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib/libturbulenceModels.so: undefined reference to `Foam::UOPstream::beginRaw(long)'
/usr/bin/ld.bfd: /usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib/libturbulenceModels.so: undefined reference to `Foam::dimensionSet::dimensionSet(Foam::dictionary const&, Foam::word const&)'
/usr/bin/ld.bfd: /usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib/libturbulenceModels.so: undefined reference to `Foam::UList<Foam::UPstream::commsStruct>::operator[](int) const'
/usr/bin/ld.bfd: /usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib/libturbulenceModels.so: undefined reference to `Foam::operator&(Foam::orientedType const&, Foam::orientedType const&)'
/usr/bin/ld.bfd: /usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib/libturbulenceModels.so: undefined reference to `Foam::profilingTrigger::profilingTrigger(char const*)'
/usr/bin/ld.bfd: /usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib/libturbulenceModels.so: undefined reference to `Foam::regIOobject::writeObject(Foam::IOstreamOption::streamFormat, Foam::IOstreamOption::versionNumber, Foam::IOstreamOption::compressionType, bool) const'
/usr/bin/ld.bfd: /usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib/libturbulenceModels.so: undefined reference to `Foam::orientedType::read(Foam::dictionary const&)'
/usr/bin/ld.bfd: /usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib/libturbulenceModels.so: undefined reference to `Foam::IOobject::globalFilePath(Foam::word const&, bool) const'
collect2: error: ld returned 1 exit status
make: *** [/opt/openfoam8/wmake/makefiles/general:142: /home/ehsan/OpenFOAM/ehsan-8/platforms/linux64GccDPInt32Opt/bin/sedFoam_rbghMULES] Error 1
`

**Comment by CyrilleBonamy** [comment]
maybe because of version 8. I check that it works on my side with version 8.

**Comment by lgy-of** [comment]
How did you deal with the first problem? I am facing the same question.

**Comment by CyrilleBonamy** [comment]
The openfoam-8 version involves a lot of changes ...
sedfoam is currently not compatible with this version of openfoam.
I encourage you to use openfoam-7 or the latest version of esi (June 2020 release from openfoam.com)

**Comment by lgy-of** [comment]
Thank you very much. I will try that.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SedFoam/sedfoam"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月27日(星期天) 凌晨0:31
收件人:&nbsp;"SedFoam/sedfoam"<sedfoam@noreply.github.com&gt;;
抄送:&nbsp;"164767701"<164767701@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [SedFoam/sedfoam] Error while making sedFoam (#27)





 
The openfoam-8 version involves a lot of changes ...
 sedfoam is currently not compatible with this version of openfoam.
 I encourage you to use openfoam-7 or the latest version of esi (June 2020 release from openfoam.com)
