### ISSUE TITLE
Compiling sedfoam on windows?

### ISSUE THREAD

**Issue by gastonfloyd** [SedFoam/sedfoam#4]
Hello,

I've been testing sedfoam for a research project and curently looking to run it on Windows platform, under blueCFD distribution (http://bluecfd.github.io/Core/). 

I'm trying to compile it but keep failing to find some files included in twophaseTurbulenceModels.C. (ee error messages below)

`$ ./Allwmake
+ TurbulenceModels/Allwmake
+ turbulenceModels/Allwmake
+ wmake libso
wmake libso .
wmakeLnInclude: linking include files to ./lnInclude
Making dependency list for source file twophaseTurbulenceModels.C
could not open file phaseIncompressibleTurbulenceModel.H for source file twophaseTurbulenceModels.C
could not open file RASModel.H for source file twophaseTurbulenceModels.C
could not open file LESModel.H for source file twophaseTurbulenceModels.C
could not open file Stokes.H for source file twophaseTurbulenceModels.C
$(/home/ofuser/blueCFD/OpenFOAM-5.x/wmake/scripts/makeReinterpretExePath x86_64-w64-mingw32-g++) -std=c++11 -Dmingw_w64 -DWM_ARCH_OPTION=64 -DWM_DP -DWM_LABEL_SIZE=32 -DWIN64 -DLITTLE_ENDIAN -DWIN64 -DLITTLE_ENDIAN -Wall -Wextra -Wold-style-cast -Wnon-virtual-dtor -Wno-unused-parameter -Wno-invalid-offsetof -O2 -DNDEBUG -gdwarf  -DNoRepository -ftemplate-depth-100 -D_FILE_OFFSET_BITS=64 -D_MODE_T_ -I. -I/home/ofuser/blueCFD/OpenFOAM-5.x/src/transportModels/compressible/lnInclude -I/home/ofuser/blueCFD/OpenFOAM-5.x/src/thermophysicalModels/basic/lnInclude -I/home/ofuser/blueCFD/OpenFOAM-5.x/src/transportModels -I/home/ofuser/blueCFD/OpenFOAM-5.x/src/transportModels/incompressible/singlePhaseTransportModel -I/home/ofuser/blueCFD/OpenFOAM-5.x/src/TurbulenceModels/turbulenceModels/lnInclude -I/home/ofuser/blueCFD/OpenFOAM-5.x/src/TurbulenceModels/incompressible/lnInclude -I/home/ofuser/blueCFD/OpenFOAM-5.x/src/TurbulenceModels/phaseIncompressible/lnInclude -I/home/ofuser/blueCFD/OpenFOAM-5.x/src/finiteVolume/lnInclude -I/home/ofuser/blueCFD/OpenFOAM-5.x/src/meshTools/lnInclude @Make/mingw_w64GccDPInt32Opt/includeHeaderPaths -IlnInclude -I. -I/home/ofuser/blueCFD/OpenFOAM-5.x/src/OpenFOAM/lnInclude -I/home/ofuser/blueCFD/OpenFOAM-5.x/src/OSspecific/MSwindows/lnInclude   -c twophaseTurbulenceModels.C -o C:/PROGRA~1/BLUECF~1/ofuser-of5/sedFoam/TurbulenceModels/turbulenceModels/Make/mingw_w64GccDPInt32Opt/twophaseTurbulenceModels.o
twophaseTurbulenceModels.C:26:10: fatal error: phaseIncompressibleTurbulenceModel.H: No such file or directory
 #include "phaseIncompressibleTurbulenceModel.H"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
`

Just wondering if you had tried sedfoam on Windows at all?

Best regards,
Gaston

**Comment by gastonfloyd** [comment]
*UPDATE*

I managed to go through the errors highlighted before, by following the recommendation posted here:
https://github.com/blueCFD/Core/wiki/Loose-notes-on-building-custom-code

This is, upper/lower case in Windows are not treated differently and its necessary to rename some files to avoid clashing while compiling OpenFOAM in Windows. 

I am now facing a different kind of error (see partial log file attached). Any ideas on how to solve this?

[sedfoam.log](https://github.com/SedFoam/sedfoam/files/2764454/sedfoam.log)



Many thanks!
Gaston

**Comment by CyrilleBonamy** [comment]
Hello,

Did you manage to use sedfoam and bluecfd?

Today, if you want to use sedfoam and windows10, I advise you to use the openfoam v1812 version directly in windows10.
To do this, follow the openfoam installation tutorial on windows10: https://openfoam.com/download/install-windows-10.php

Please note that sedfoam is not expected to support bluecdf
