### ISSUE TITLE
codeSteam error

### ISSUE THREAD

**Issue by ramapathakota05** [SedFoam/sedfoam#48]
![error](https://user-images.githubusercontent.com/65251211/107998173-6e5cdd00-6fdc-11eb-9441-2ba381448224.png)

Hi,

I have been trying to run the seafoam tutorial and ended up getting the error as shown in the attached screenshot...I think it is do with the initialisation..Any help much appreciate.

Regards

**Comment by CyrilleBonamy** [comment]
Thanks for opening an issue.  :-)

I think the problem is related to your openfoam version.
If you carefully read lines 55 to 58, you will have the solution : https://github.com/SedFoam/sedfoam/blob/master/tutorials/1DBedLoad/0_org/alpha_a#L55

More concretely :
In the file 0_org/alpha_a, comment the line 56 and uncomment the line 58, ./Allclean   ./Allrun

**Comment by ramapathakota05** [comment]
great thanks for coming back...yeh I managed to fix it after posting it here :-).. 

Also, tried to run the 2DPipelineScour case but it's failing due to ClipUa error as shown in the screenshot....could you please check this out and let me know how to fix this. 
![error](https://user-images.githubusercontent.com/65251211/108098907-d8788f00-707b-11eb-8165-137c3577786d.png)

**Comment by mathieu7an** [comment]
Hi !

Can you try to replace the line:
 `ClipUa          1;` 
in the file _constant/forceProperties_ by the line:
 `ClipUa          ClipUa [ 0 0 0 0 0 ] 1;`
and tell us if it solved the problem ?

Best regards,

Antoine

**Comment by ramapathakota05** [comment]
Hi
Thanks, that fixed and it's running now.

Also, I'm trying to run the 3DScour tutorial and  have the following error when trying to initialize the alpha field using "funkySetFields -time 0" 

--> FOAM FATAL IO ERROR:
Unknown patchField type kqRWallFunction for patch type wall

Please may I know how could I fix this too?

Regards

**Comment by ramap1219** [comment]
Hi

Just wanted to update you that changing the Cylinder boundary field Type to **fixedValue** has fixed the above issue for both k and omega fields.
Please advise if this is going to affect results?
Regards

**Comment by CyrilleBonamy** [comment]
Concerning the funkySetFields issue, i fixed the problem here: https://github.com/SedFoam/sedfoam/blob/master/tutorials/3DScour/system/controlDict#L57 

Thanks again for creating an issue.
