### ISSUE TITLE
openfoam 7 

### ISSUE THREAD

**Issue by ramap1219** [SedFoam/sedfoam#61]
Hi,
I'm trying to install sedFoam on OpenFOAM 7 and it is failing due to the error shown below screenshot...

I was able to install it successfully a few months ago but strangely it is failing now...I suspect it's due to the new changes in the code..Please advise.

![image](https://user-images.githubusercontent.com/79201409/116215436-9769be80-a73f-11eb-8891-7ec2fd18a98b.png)

**Comment by CyrilleBonamy** [comment]
Hello,

I need to update the README but now we only support the ESI openfoam version : openfoam.com
Thus, the openfoam.org version (7) is not directly supported.

Cyrille

**Comment by ramap1219** [comment]
Hi, 
Unfortunately we were not able to compile the swak4Foam with openFoam v2012, which has following error message. Any suggestions how it can be fixed pls?
![image](https://user-images.githubusercontent.com/79201409/116684287-b3bc6400-a9a8-11eb-8cb7-aaf398ec94de.png)

**Comment by ramap1219** [comment]
hiya,
Just to update we manage to compile the sedFoam for OF v2012 and also swak4foam too by checking out developer branch "git checkout branches/develop"...

we are now running a 3D tutorial and it is taking about 2hrs to perform 0.4s on 280cores...could you please recon if there is a way to improve the computational time...we are going to try increasing maxDelT and courant number...however, wondering if you have a better suggestion in improving the computational time.

Thanks

**Comment by jchauchat** [comment]
Hi,
here the citation from Nagel et al. AWR 2020 paper:
"The reference two-phase flow simulation was run for 600 s of real time. This computation took approximately 480 h (20 days) on 224 processors Intel®Xeon®E5-2690 v4. The compu- tational time is approximatively of 108,000 CPU hours, which would correspond roughly to 12 years on a single processor."

Meaning that your run is 5 times slower than ours. 

I don't have the log files but here is what we used in controlDict:
maxCo           0.6;

maxAlphaCo      0.6;

maxDeltaT       2e-3;

meanding that maxDeltaT is larger but you may have to increase it progressively to maintain stability at the early stage of the simulation.

Best regards,
Julien
