### ISSUE TITLE
improve compile locations

### ISSUE THREAD

**Issue by olesenm** [SedFoam/sedfoam#86]
Currently only compiles into user locations. Adjust Make files to support different locations.

**Comment by olesenm** [comment]
- will address this myself - will submit a merge request accordingly.

**Comment by CyrilleBonamy** [comment]
For this point there is a special branch (module_openfoam.com) which compiles in FOAM_BIN and FOAM_LIB locations.

But just now this branch is not up to date

And we are very happy if you submit a merge request. :-)

**Comment by olesenm** [comment]
Hi @CyrilleBonamy - glad I caught this ahead of time.
Indeed we want to use the FOAM_MODULE_xxx values with the corresponding changes to the Make/{files,options}.

This makes the compilation targets completely flexible and has been written to be _failsafe_ - it will work with any OpenFOAM versions or flavours.

Can even do something like this: `./Allwmake -s -j -prefix=/tmp/test-install-sedfoam` if that is what you want. In addition to the standard known short-cuts (see `wmake -help-full`) we also have special _none_ and _false_ predefined types.

So if I am doing an OpenFOAM rebuild and don't want any modules: `./Allwmake -s -j -l -prefix=none`
