### ISSUE TITLE
update docker and ci pipelines

### ISSUE THREAD

**Issue by olesenm** [SedFoam/sedfoam#90]
The openfoam2012 docker image is now ubuntu based: 

- https://develop.openfoam.com/Development/openfoam/-/wikis/precompiled/docker
- https://develop.openfoam.com/packaging/containers

**Comment by CyrilleBonamy** [comment]
Done :-)    #91

**Comment by olesenm** [comment]
Your decision, but might want to use the entry points and the "openfoam-docker" run script. This lets you mount the current directory (and a data directory) with the same uid/gid as on the host system, which can makes things a bit cleaner.

In the future, might also be easy to source "/openfoam/bash.rc"  instead of using longer /usr/lib/openfoam/xxxx paths.

With the recent module changes, could also consider compiling sedFoam with `./Allwmake -prefix=group`, which should place the output into `/usr/lib/openfoam/openfoam2106/site/2106/platforms/linux64GccDPInt32Opt/{bin,lib}` and thus will look like part of the regular OpenFOAM install for subsequent uses of the image.

For the swak bits, can try some switching about [like we have for spack](https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/openfoam/common/change-userdir.sh), or simply assign FOAM_USER_APPBIN=$FOAM_SITE_APPBIN before starting compilation.

**Comment by CyrilleBonamy** [comment]
I updated the docker and continuous integration accordingly to your advice.
Regarding the "openfoam-docker" run script, i understand the interest and i will try to adapt it one to sedfoam in the coming weeks (months?).
Thank you very much again.
